version: '3'

tasks:
  default:
    desc: "Run linter and tests"
    cmds:
      - task: lint
      - task: test

  install:
    desc: "Install dependencies"
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go mod tidy

  lint:
    desc: "Run linter"
    cmds:
      - golangci-lint run ./...

  test:
    desc: "Run tests with coverage"
    cmds:
      - go test -cover ./...
      
  gen-proto:
    desc: "Clean and generate proto files"
    cmds:
      - chmod +x ./scripts/clean-proto.sh
      - ./scripts/clean-proto.sh
      - chmod +x ./scripts/gen-proto.sh
      - ./scripts/gen-proto.sh