// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/v1/orchestrator/orchestrator.proto

package orchestratorv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CalculationStatus определяет статус вычисления.
type CalculationStatus int32

const (
	// Вычисление ожидает выполнения.
	CalculationStatus_PENDING CalculationStatus = 0
	// Вычисление в процессе выполнения.
	CalculationStatus_IN_PROGRESS CalculationStatus = 1
	// Вычисление успешно завершено.
	CalculationStatus_COMPLETED CalculationStatus = 2
	// Вычисление завершилось с ошибкой.
	CalculationStatus_ERROR CalculationStatus = 3
)

// Enum value maps for CalculationStatus.
var (
	CalculationStatus_name = map[int32]string{
		0: "PENDING",
		1: "IN_PROGRESS",
		2: "COMPLETED",
		3: "ERROR",
	}
	CalculationStatus_value = map[string]int32{
		"PENDING":     0,
		"IN_PROGRESS": 1,
		"COMPLETED":   2,
		"ERROR":       3,
	}
)

func (x CalculationStatus) Enum() *CalculationStatus {
	p := new(CalculationStatus)
	*p = x
	return p
}

func (x CalculationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalculationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_orchestrator_orchestrator_proto_enumTypes[0].Descriptor()
}

func (CalculationStatus) Type() protoreflect.EnumType {
	return &file_proto_v1_orchestrator_orchestrator_proto_enumTypes[0]
}

func (x CalculationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalculationStatus.Descriptor instead.
func (CalculationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

// OperationStatus определяет статус операции.
type OperationStatus int32

const (
	// Операция ожидает выполнения.
	OperationStatus_OPERATION_PENDING OperationStatus = 0
	// Операция в процессе выполнения.
	OperationStatus_OPERATION_IN_PROGRESS OperationStatus = 1
	// Операция успешно завершена.
	OperationStatus_OPERATION_COMPLETED OperationStatus = 2
	// Операция завершилась с ошибкой.
	OperationStatus_OPERATION_ERROR OperationStatus = 3
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_PENDING",
		1: "OPERATION_IN_PROGRESS",
		2: "OPERATION_COMPLETED",
		3: "OPERATION_ERROR",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_PENDING":     0,
		"OPERATION_IN_PROGRESS": 1,
		"OPERATION_COMPLETED":   2,
		"OPERATION_ERROR":       3,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_orchestrator_orchestrator_proto_enumTypes[1].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_proto_v1_orchestrator_orchestrator_proto_enumTypes[1]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_orchestrator_orchestrator_proto_rawDescGZIP(), []int{1}
}

// OperationType определяет тип арифметической операции.
type OperationType int32

const (
	// Неопределенная операция.
	OperationType_TYPE_UNSPECIFIED OperationType = 0
	// Сложение.
	OperationType_TYPE_ADDITION OperationType = 1
	// Вычитание.
	OperationType_TYPE_SUBTRACTION OperationType = 2
	// Умножение.
	OperationType_TYPE_MULTIPLICATION OperationType = 3
	// Деление.
	OperationType_TYPE_DIVISION OperationType = 4
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_ADDITION",
		2: "TYPE_SUBTRACTION",
		3: "TYPE_MULTIPLICATION",
		4: "TYPE_DIVISION",
	}
	OperationType_value = map[string]int32{
		"TYPE_UNSPECIFIED":    0,
		"TYPE_ADDITION":       1,
		"TYPE_SUBTRACTION":    2,
		"TYPE_MULTIPLICATION": 3,
		"TYPE_DIVISION":       4,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_orchestrator_orchestrator_proto_enumTypes[2].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_v1_orchestrator_orchestrator_proto_enumTypes[2]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_orchestrator_orchestrator_proto_rawDescGZIP(), []int{2}
}

// Запрос на вычисление выражения.
type CalculateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Арифметическое выражение для вычисления.
	Expression    string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// Ответ с деталями вычисления.
type CalculateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор для отслеживания вычисления.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Текущий статус вычисления.
	Status CalculationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=orchestrator.v1.CalculationStatus" json:"status,omitempty"`
	// Результат, если вычисление завершено.
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Сообщение об ошибке, если вычисление не удалось.
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_orchestrator_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CalculateResponse) GetStatus() CalculationStatus {
	if x != nil {
		return x.Status
	}
	return CalculationStatus_PENDING
}

func (x *CalculateResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CalculateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Запрос на получение деталей вычисления по ID.
type GetCalculationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор вычисления.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalculationRequest) Reset() {
	*x = GetCalculationRequest{}
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalculationRequest) ProtoMessage() {}

func (x *GetCalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalculationRequest.ProtoReflect.Descriptor instead.
func (*GetCalculationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_orchestrator_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetCalculationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ с деталями вычисления.
type GetCalculationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор вычисления.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Идентификатор пользователя.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Исходное выражение.
	Expression string `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	// Результат вычисления.
	Result string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	// Статус вычисления.
	Status CalculationStatus `protobuf:"varint,5,opt,name=status,proto3,enum=orchestrator.v1.CalculationStatus" json:"status,omitempty"`
	// Сообщение об ошибке.
	ErrorMessage string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Время создания.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Время последнего обновления.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalculationResponse) Reset() {
	*x = GetCalculationResponse{}
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalculationResponse) ProtoMessage() {}

func (x *GetCalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalculationResponse.ProtoReflect.Descriptor instead.
func (*GetCalculationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_orchestrator_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *GetCalculationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCalculationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCalculationResponse) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *GetCalculationResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetCalculationResponse) GetStatus() CalculationStatus {
	if x != nil {
		return x.Status
	}
	return CalculationStatus_PENDING
}

func (x *GetCalculationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetCalculationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetCalculationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Ответ со списком вычислений.
type ListCalculationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список вычислений.
	Calculations  []*GetCalculationResponse `protobuf:"bytes,1,rep,name=calculations,proto3" json:"calculations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCalculationsResponse) Reset() {
	*x = ListCalculationsResponse{}
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCalculationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCalculationsResponse) ProtoMessage() {}

func (x *ListCalculationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_orchestrator_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCalculationsResponse.ProtoReflect.Descriptor instead.
func (*ListCalculationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_orchestrator_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *ListCalculationsResponse) GetCalculations() []*GetCalculationResponse {
	if x != nil {
		return x.Calculations
	}
	return nil
}

var File_proto_v1_orchestrator_orchestrator_proto protoreflect.FileDescriptor

const file_proto_v1_orchestrator_orchestrator_proto_rawDesc = "" +
	"\n" +
	"(proto/v1/orchestrator/orchestrator.proto\x12\x0forchestrator.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"2\n" +
	"\x10CalculateRequest\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\"\x9c\x01\n" +
	"\x11CalculateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".orchestrator.v1.CalculationStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"'\n" +
	"\x15GetCalculationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd0\x02\n" +
	"\x16GetCalculationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"expression\x18\x03 \x01(\tR\n" +
	"expression\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12:\n" +
	"\x06status\x18\x05 \x01(\x0e2\".orchestrator.v1.CalculationStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"g\n" +
	"\x18ListCalculationsResponse\x12K\n" +
	"\fcalculations\x18\x01 \x03(\v2'.orchestrator.v1.GetCalculationResponseR\fcalculations*K\n" +
	"\x11CalculationStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03*q\n" +
	"\x0fOperationStatus\x12\x15\n" +
	"\x11OPERATION_PENDING\x10\x00\x12\x19\n" +
	"\x15OPERATION_IN_PROGRESS\x10\x01\x12\x17\n" +
	"\x13OPERATION_COMPLETED\x10\x02\x12\x13\n" +
	"\x0fOPERATION_ERROR\x10\x03*z\n" +
	"\rOperationType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTYPE_ADDITION\x10\x01\x12\x14\n" +
	"\x10TYPE_SUBTRACTION\x10\x02\x12\x17\n" +
	"\x13TYPE_MULTIPLICATION\x10\x03\x12\x11\n" +
	"\rTYPE_DIVISION\x10\x042\x83\x03\n" +
	"\x13OrchestratorService\x12p\n" +
	"\tCalculate\x12!.orchestrator.v1.CalculateRequest\x1a\".orchestrator.v1.CalculateResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/calculate\x12\x84\x01\n" +
	"\x0eGetCalculation\x12&.orchestrator.v1.GetCalculationRequest\x1a'.orchestrator.v1.GetCalculationResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/calculations/{id}\x12s\n" +
	"\x10ListCalculations\x12\x16.google.protobuf.Empty\x1a).orchestrator.v1.ListCalculationsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/calculationsBWZUgithub.com/flexer2006/y.lms-final-task-calc-go/pkg/api/orchestrator/v1;orchestratorv1b\x06proto3"

var (
	file_proto_v1_orchestrator_orchestrator_proto_rawDescOnce sync.Once
	file_proto_v1_orchestrator_orchestrator_proto_rawDescData []byte
)

func file_proto_v1_orchestrator_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_v1_orchestrator_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_v1_orchestrator_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_orchestrator_orchestrator_proto_rawDesc), len(file_proto_v1_orchestrator_orchestrator_proto_rawDesc)))
	})
	return file_proto_v1_orchestrator_orchestrator_proto_rawDescData
}

var file_proto_v1_orchestrator_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_v1_orchestrator_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_orchestrator_orchestrator_proto_goTypes = []any{
	(CalculationStatus)(0),           // 0: orchestrator.v1.CalculationStatus
	(OperationStatus)(0),             // 1: orchestrator.v1.OperationStatus
	(OperationType)(0),               // 2: orchestrator.v1.OperationType
	(*CalculateRequest)(nil),         // 3: orchestrator.v1.CalculateRequest
	(*CalculateResponse)(nil),        // 4: orchestrator.v1.CalculateResponse
	(*GetCalculationRequest)(nil),    // 5: orchestrator.v1.GetCalculationRequest
	(*GetCalculationResponse)(nil),   // 6: orchestrator.v1.GetCalculationResponse
	(*ListCalculationsResponse)(nil), // 7: orchestrator.v1.ListCalculationsResponse
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 9: google.protobuf.Empty
}
var file_proto_v1_orchestrator_orchestrator_proto_depIdxs = []int32{
	0, // 0: orchestrator.v1.CalculateResponse.status:type_name -> orchestrator.v1.CalculationStatus
	0, // 1: orchestrator.v1.GetCalculationResponse.status:type_name -> orchestrator.v1.CalculationStatus
	8, // 2: orchestrator.v1.GetCalculationResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 3: orchestrator.v1.GetCalculationResponse.updated_at:type_name -> google.protobuf.Timestamp
	6, // 4: orchestrator.v1.ListCalculationsResponse.calculations:type_name -> orchestrator.v1.GetCalculationResponse
	3, // 5: orchestrator.v1.OrchestratorService.Calculate:input_type -> orchestrator.v1.CalculateRequest
	5, // 6: orchestrator.v1.OrchestratorService.GetCalculation:input_type -> orchestrator.v1.GetCalculationRequest
	9, // 7: orchestrator.v1.OrchestratorService.ListCalculations:input_type -> google.protobuf.Empty
	4, // 8: orchestrator.v1.OrchestratorService.Calculate:output_type -> orchestrator.v1.CalculateResponse
	6, // 9: orchestrator.v1.OrchestratorService.GetCalculation:output_type -> orchestrator.v1.GetCalculationResponse
	7, // 10: orchestrator.v1.OrchestratorService.ListCalculations:output_type -> orchestrator.v1.ListCalculationsResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_v1_orchestrator_orchestrator_proto_init() }
func file_proto_v1_orchestrator_orchestrator_proto_init() {
	if File_proto_v1_orchestrator_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_orchestrator_orchestrator_proto_rawDesc), len(file_proto_v1_orchestrator_orchestrator_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_orchestrator_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_v1_orchestrator_orchestrator_proto_depIdxs,
		EnumInfos:         file_proto_v1_orchestrator_orchestrator_proto_enumTypes,
		MessageInfos:      file_proto_v1_orchestrator_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_v1_orchestrator_orchestrator_proto = out.File
	file_proto_v1_orchestrator_orchestrator_proto_goTypes = nil
	file_proto_v1_orchestrator_orchestrator_proto_depIdxs = nil
}
