// Package errors содержит ошибки для домена.
package errors

import "errors"

var (
	ErrNoAgentsAvailable    = errors.New("no agents available for operation")
	ErrOperationFailed      = errors.New("operation execution failed")
	ErrMaxRetriesExceeded   = errors.New("maximum retries exceeded")
	ErrContextCanceled      = errors.New("context canceled")
	ErrNilOperation         = errors.New("operation cannot be nil")
	ErrNilPool              = errors.New("agent pool cannot be nil")
	ErrInvalidOperationID   = errors.New("invalid operation ID")
	ErrAgentNotFound        = errors.New("agent not found")
	ErrInvalidCapacity      = errors.New("invalid agent capacity")
	ErrNilStorage           = errors.New("agent storage cannot be nil")
	ErrNilOperationRepo     = errors.New("operation repository cannot be nil")
	ErrPoolAlreadyStopped   = errors.New("agent pool already stopped")
	ErrOperationAssignment  = errors.New("failed to assign operation to agent")
	ErrInvalidOperationType = errors.New("invalid operation type")
	ErrPoolNotRunning       = errors.New("agent pool is not running")
	ErrNilWorkerStatus      = errors.New("worker returned nil status")
	ErrAgentNotRunning      = errors.New("agent is not running or not online")
	ErrAgentAtCapacity      = errors.New("agent is at full capacity")
	ErrQueueFull            = errors.New("operation queue is full")
	ErrInvalidOperand       = errors.New("invalid operand")
	ErrDivisionByZero       = errors.New("division by zero")
	ErrUnsupportedOp        = errors.New("unsupported operation type")
	ErrRepoNotInitialized   = errors.New("operation repository not initialized")
	ErrInvalidReferenceID   = errors.New("invalid reference ID")
	ErrReferenceNotFound    = errors.New("referenced operation not found")
	ErrRefNotCompleted      = errors.New("referenced operation not completed")
)

var (
	ErrUserAlreadyExists   = errors.New("user already exists")
	ErrInvalidCredentials  = errors.New("invalid login or password")
	ErrUserNotFound        = errors.New("user not found")
	ErrInvalidToken        = errors.New("invalid token")
	ErrTokenExpired        = errors.New("token expired")
	ErrTokenNotFound       = errors.New("token not found")
	ErrTokenRevoked        = errors.New("token revoked")
	ErrInternalServerError = errors.New("internal server error")
)

var (
	ErrInvalidExpression       = errors.New("invalid expression")
	ErrInvalidUserID           = errors.New("invalid user ID")
	ErrCalculationNotFound     = errors.New("calculation not found")
	ErrUnauthorizedAccess      = errors.New("unauthorized access to calculation")
	ErrOperationCreationFailed = errors.New("failed to create operations")
	ErrInternalError           = errors.New("internal server error")
	ErrUseCaseNil              = errors.New("use case is nil")
	ErrCalcRepoNil             = errors.New("calculation repository is nil")
	ErrOpRepoNil               = errors.New("operation repository is nil")
	ErrSpecificCalcNotFound    = errors.New("calculation not found with ID")
	ErrTooManyOps              = errors.New("expression too complex, too many operations")
	ErrCreateOps               = errors.New("failed to create operations")
	ErrInvalidOperation        = errors.New("invalid operation")
	ErrOperationNotFound       = errors.New("operation not found")
	ErrNilDependency           = errors.New("nil dependency provided")
	ErrPanic                   = errors.New("panic in operation")
	ErrContextDone             = errors.New("context canceled")
	ErrNilExecutor             = errors.New("operation executor cannot be nil")
	ErrNilRepository           = errors.New("repository cannot be nil")
	ErrEvalError               = errors.New("expression evaluation error")
	ErrPoolAssignFailure       = errors.New("failed to assign operation to agent")
	ErrNoAgentAvailable        = errors.New("no agent available for operation")
	ErrInvalidArgs             = errors.New("invalid arguments")
)
