// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/v1/agent/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на выполнение операции.
type PerformOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор операции.
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// ID вычисления, к которому относится операция.
	CalculationId string `protobuf:"bytes,2,opt,name=calculation_id,json=calculationId,proto3" json:"calculation_id,omitempty"`
	// Тип арифметической операции.
	OperationType int32 `protobuf:"varint,3,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	// Первый операнд.
	Operand1 string `protobuf:"bytes,4,opt,name=operand1,proto3" json:"operand1,omitempty"`
	// Второй операнд.
	Operand2      string `protobuf:"bytes,5,opt,name=operand2,proto3" json:"operand2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformOperationRequest) Reset() {
	*x = PerformOperationRequest{}
	mi := &file_proto_v1_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformOperationRequest) ProtoMessage() {}

func (x *PerformOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformOperationRequest.ProtoReflect.Descriptor instead.
func (*PerformOperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PerformOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *PerformOperationRequest) GetCalculationId() string {
	if x != nil {
		return x.CalculationId
	}
	return ""
}

func (x *PerformOperationRequest) GetOperationType() int32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

func (x *PerformOperationRequest) GetOperand1() string {
	if x != nil {
		return x.Operand1
	}
	return ""
}

func (x *PerformOperationRequest) GetOperand2() string {
	if x != nil {
		return x.Operand2
	}
	return ""
}

// Ответ с результатом операции.
type PerformOperationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор операции.
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Результат операции.
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	// Успешность выполнения операции.
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// Сообщение об ошибке, если операция не удалась.
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Время выполнения операции в миллисекундах.
	ProcessingTimeMs int64 `protobuf:"varint,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PerformOperationResponse) Reset() {
	*x = PerformOperationResponse{}
	mi := &file_proto_v1_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformOperationResponse) ProtoMessage() {}

func (x *PerformOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformOperationResponse.ProtoReflect.Descriptor instead.
func (*PerformOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PerformOperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *PerformOperationResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *PerformOperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PerformOperationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PerformOperationResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Запрос на проверку работоспособности.
type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_proto_v1_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_agent_proto_rawDescGZIP(), []int{2}
}

// Ответ на проверку работоспособности.
type HealthcheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Работоспособность.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Версия агента.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// ID агента.
	AgentId       string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_proto_v1_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthcheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthcheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthcheckResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Запрос на получение статуса агента.
type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_proto_v1_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_agent_proto_rawDescGZIP(), []int{4}
}

// Ответ с деталями статуса агента.
type GetAgentStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID агента.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Статус агента.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Текущая нагрузка.
	CurrentLoad int32 `protobuf:"varint,3,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	// Максимальная емкость.
	MaxCapacity int32 `protobuf:"varint,4,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	// Время обработки операций в миллисекундах.
	OperationCosts map[string]int32 `protobuf:"bytes,5,rep,name=operation_costs,json=operationCosts,proto3" json:"operation_costs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Статистика о выполненных операциях.
	OperationsCompleted int64 `protobuf:"varint,6,opt,name=operations_completed,json=operationsCompleted,proto3" json:"operations_completed,omitempty"`
	OperationsFailed    int64 `protobuf:"varint,7,opt,name=operations_failed,json=operationsFailed,proto3" json:"operations_failed,omitempty"`
	UptimeSeconds       int64 `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAgentStatusResponse) Reset() {
	*x = GetAgentStatusResponse{}
	mi := &file_proto_v1_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusResponse) ProtoMessage() {}

func (x *GetAgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentStatusResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetAgentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAgentStatusResponse) GetCurrentLoad() int32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *GetAgentStatusResponse) GetMaxCapacity() int32 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *GetAgentStatusResponse) GetOperationCosts() map[string]int32 {
	if x != nil {
		return x.OperationCosts
	}
	return nil
}

func (x *GetAgentStatusResponse) GetOperationsCompleted() int64 {
	if x != nil {
		return x.OperationsCompleted
	}
	return 0
}

func (x *GetAgentStatusResponse) GetOperationsFailed() int64 {
	if x != nil {
		return x.OperationsFailed
	}
	return 0
}

func (x *GetAgentStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_proto_v1_agent_agent_proto protoreflect.FileDescriptor

const file_proto_v1_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/agent/agent.proto\x12\bagent.v1\"\xc2\x01\n" +
	"\x17PerformOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0ecalculation_id\x18\x02 \x01(\tR\rcalculationId\x12%\n" +
	"\x0eoperation_type\x18\x03 \x01(\x05R\roperationType\x12\x1a\n" +
	"\boperand1\x18\x04 \x01(\tR\boperand1\x12\x1a\n" +
	"\boperand2\x18\x05 \x01(\tR\boperand2\"\xc2\x01\n" +
	"\x18PerformOperationResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x03R\x10processingTimeMs\"\x14\n" +
	"\x12HealthcheckRequest\"d\n" +
	"\x13HealthcheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"\x17\n" +
	"\x15GetAgentStatusRequest\"\xba\x03\n" +
	"\x16GetAgentStatusResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_load\x18\x03 \x01(\x05R\vcurrentLoad\x12!\n" +
	"\fmax_capacity\x18\x04 \x01(\x05R\vmaxCapacity\x12]\n" +
	"\x0foperation_costs\x18\x05 \x03(\v24.agent.v1.GetAgentStatusResponse.OperationCostsEntryR\x0eoperationCosts\x121\n" +
	"\x14operations_completed\x18\x06 \x01(\x03R\x13operationsCompleted\x12+\n" +
	"\x11operations_failed\x18\a \x01(\x03R\x10operationsFailed\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\x1aA\n" +
	"\x13OperationCostsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\x8a\x02\n" +
	"\fAgentService\x12Y\n" +
	"\x10PerformOperation\x12!.agent.v1.PerformOperationRequest\x1a\".agent.v1.PerformOperationResponse\x12J\n" +
	"\vHealthcheck\x12\x1c.agent.v1.HealthcheckRequest\x1a\x1d.agent.v1.HealthcheckResponse\x12S\n" +
	"\x0eGetAgentStatus\x12\x1f.agent.v1.GetAgentStatusRequest\x1a .agent.v1.GetAgentStatusResponseBIZGgithub.com/flexer2006/y.lms-final-task-calc-go/pkg/api/agent/v1;agentv1b\x06proto3"

var (
	file_proto_v1_agent_agent_proto_rawDescOnce sync.Once
	file_proto_v1_agent_agent_proto_rawDescData []byte
)

func file_proto_v1_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_v1_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_v1_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_agent_agent_proto_rawDesc), len(file_proto_v1_agent_agent_proto_rawDesc)))
	})
	return file_proto_v1_agent_agent_proto_rawDescData
}

var file_proto_v1_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_v1_agent_agent_proto_goTypes = []any{
	(*PerformOperationRequest)(nil),  // 0: agent.v1.PerformOperationRequest
	(*PerformOperationResponse)(nil), // 1: agent.v1.PerformOperationResponse
	(*HealthcheckRequest)(nil),       // 2: agent.v1.HealthcheckRequest
	(*HealthcheckResponse)(nil),      // 3: agent.v1.HealthcheckResponse
	(*GetAgentStatusRequest)(nil),    // 4: agent.v1.GetAgentStatusRequest
	(*GetAgentStatusResponse)(nil),   // 5: agent.v1.GetAgentStatusResponse
	nil,                              // 6: agent.v1.GetAgentStatusResponse.OperationCostsEntry
}
var file_proto_v1_agent_agent_proto_depIdxs = []int32{
	6, // 0: agent.v1.GetAgentStatusResponse.operation_costs:type_name -> agent.v1.GetAgentStatusResponse.OperationCostsEntry
	0, // 1: agent.v1.AgentService.PerformOperation:input_type -> agent.v1.PerformOperationRequest
	2, // 2: agent.v1.AgentService.Healthcheck:input_type -> agent.v1.HealthcheckRequest
	4, // 3: agent.v1.AgentService.GetAgentStatus:input_type -> agent.v1.GetAgentStatusRequest
	1, // 4: agent.v1.AgentService.PerformOperation:output_type -> agent.v1.PerformOperationResponse
	3, // 5: agent.v1.AgentService.Healthcheck:output_type -> agent.v1.HealthcheckResponse
	5, // 6: agent.v1.AgentService.GetAgentStatus:output_type -> agent.v1.GetAgentStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_agent_agent_proto_init() }
func file_proto_v1_agent_agent_proto_init() {
	if File_proto_v1_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_agent_agent_proto_rawDesc), len(file_proto_v1_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_v1_agent_agent_proto_depIdxs,
		MessageInfos:      file_proto_v1_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_v1_agent_agent_proto = out.File
	file_proto_v1_agent_agent_proto_goTypes = nil
	file_proto_v1_agent_agent_proto_depIdxs = nil
}
